# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'random_password.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import string 
import random

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(388, 575)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.generate = QtWidgets.QPushButton(self.centralwidget)
        self.generate.setGeometry(QtCore.QRect(30, 390, 331, 161))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.generate.setFont(font)
        self.generate.setStyleSheet("background-color: rgb(115, 210, 22);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 50px;")
        self.generate.setObjectName("generate")
        self.password_show = QtWidgets.QLabel(self.centralwidget)
        self.password_show.setGeometry(QtCore.QRect(204, 120, 191, 71))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.password_show.setFont(font)
        self.password_show.setStyleSheet("color: rgb(32, 74, 135);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(9, 41, 4, 255), stop:0.085 rgba(2, 79, 0, 255), stop:0.19 rgba(50, 147, 22, 255), stop:0.275 rgba(236, 191, 49, 255), stop:0.39 rgba(243, 61, 34, 255), stop:0.555 rgba(135, 81, 60, 255), stop:0.667 rgba(121, 75, 255, 255), stop:0.825 rgba(164, 255, 244, 255), stop:0.885 rgba(104, 222, 71, 255), stop:1 rgba(93, 128, 0, 255));\n"
"background-color: rgb(233, 185, 110);")
        self.password_show.setText("")
        self.password_show.setObjectName("password_show")
        self.passwordbuyrugi = QtWidgets.QLabel(self.centralwidget)
        self.passwordbuyrugi.setGeometry(QtCore.QRect(0, 120, 205, 71))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.passwordbuyrugi.setFont(font)
        self.passwordbuyrugi.setStyleSheet("background-color: rgb(114, 159, 207);\n"
"color: rgb(238, 238, 236);")
        self.passwordbuyrugi.setObjectName("passwordbuyrugi")
        self.nom = QtWidgets.QLabel(self.centralwidget)
        self.nom.setGeometry(QtCore.QRect(0, 40, 391, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.nom.setFont(font)
        self.nom.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(239, 41, 41);")
        self.nom.setObjectName("nom")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.actionNew_File = QtWidgets.QAction(MainWindow)
        self.actionNew_File.setObjectName("actionNew_File")
        self.actionOpen_File = QtWidgets.QAction(MainWindow)
        self.actionOpen_File.setObjectName("actionOpen_File")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionSave_all = QtWidgets.QAction(MainWindow)
        self.actionSave_all.setObjectName("actionSave_all")
        self.actionPrint = QtWidgets.QAction(MainWindow)
        self.actionPrint.setObjectName("actionPrint")
        self.actionPrint_Preview = QtWidgets.QAction(MainWindow)
        self.actionPrint_Preview.setObjectName("actionPrint_Preview")
        self.actionExport_PDF = QtWidgets.QAction(MainWindow)
        self.actionExport_PDF.setObjectName("actionExport_PDF")
        self.actionCopy = QtWidgets.QAction(MainWindow)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtWidgets.QAction(MainWindow)
        self.actionPaste.setObjectName("actionPaste")
        self.actionPaste_2 = QtWidgets.QAction(MainWindow)
        self.actionPaste_2.setObjectName("actionPaste_2")
        self.actionAbout_dev = QtWidgets.QAction(MainWindow)
        self.actionAbout_dev.setObjectName("actionAbout_dev")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.generate.clicked.connect(self.password_yarat)

        def password_yarat(self):
            chiqar = self.nom.text()
            s = 8
            ran = ".join(random.choices(string.ascii_uppercase + ascii_lowercase + string.digits, k = s))"
            print(str(ran))





    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.generate.setText(_translate("MainWindow", "Generate"))
        self.passwordbuyrugi.setText(_translate("MainWindow", "  Suggested Password: "))
        self.nom.setText(_translate("MainWindow", "            Random Password"))
        self.actionNew_File.setText(_translate("MainWindow", "New File"))
        self.actionOpen_File.setText(_translate("MainWindow", "Open File"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_as.setText(_translate("MainWindow", "Save As..."))
        self.actionSave_all.setText(_translate("MainWindow", "Save All"))
        self.actionPrint.setText(_translate("MainWindow", "Print"))
        self.actionPrint_Preview.setText(_translate("MainWindow", "Print Preview"))
        self.actionExport_PDF.setText(_translate("MainWindow", "Export PDF"))
        self.actionCopy.setText(_translate("MainWindow", "Copy"))
        self.actionPaste.setText(_translate("MainWindow", "Cut"))
        self.actionPaste_2.setText(_translate("MainWindow", "Paste"))
        self.actionAbout_dev.setText(_translate("MainWindow", "About dev"))


